---
- name: Preconfig
  hosts: demo
  tasks:
    - name: Установка Docker
      become: yes
      block:

        - name: Install ca-certificates + curl
          apt:
            update_cache: true
            cache_valid_time: 3600
            pkg:
              - ca-certificates
              - curl
          register: out

        - name: Debug
          debug:
            var: out

        - name: Make keyrings directory
          shell: install -m 0755 -d /etc/apt/keyrings

        - name: Curl docker keyrings
          get_url:
            url: https://download.docker.com/linux/debian/gpg
            dest: /etc/apt/keyrings/docker.asc

        - name: Установка стабильного репозитория docker
          apt_repository:
            repo:
              "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] 
              https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
            filename: docker
            update_cache: true
            state: present

        - name: Install DOCKER
          apt:
            update_cache: true
            cache_valid_time: 3600
            pkg:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-buildx-plugin
              - docker-compose-plugin

        - name: Проверка что Docker установлен и перезагружен
          service:
            name: docker
            state: restarted
            enabled: yes
