---
- name: user
  hosts: demo
  vars_files:
    - ./my_vars.yml
  tasks:
    - name: Create user
#      vars:
#        user: superuser
      user:
        name: "{{ user }}"
        state: present
      become: true
